language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
gemfile:
  - gemfiles/rspec2_1.gemfile
  - gemfiles/rspec3_0.gemfile
script: CODECLIMATE_REPO_TOKEN=329887587f83c7ce5a1ab75f426c00830ba5ffac290c90bc486713c88baea900 bundle exec rspec
branches:
  only:
    - master
notifications:
  email: false
